from pathlib import Path

DEFAULT_SENTENCE_PAUSE_S = 0.2
DEFAULT_WAVEGLOW = "pretrained_v5"
DEFAULT_WAVEGLOW_VERSION = 5
DEFAULT_SIGMA = 1.0
DEFAULT_DENOISER_STRENGTH = 0.0005
DEFAULT_SEED = 1111
DEFAULT_READ_MEL_INFO_PATH = Path("/tmp/mel_out.json")
DEFAULT_SAVE_WAV_INFO_COPY_PATH = Path("/tmp/wav_out.json")
