DEFAULT_SENTENCE_PAUSE_S = 0.2
DEFAULT_WAVEGLOW = "pretrained_v3"
DEFAULT_WAVEGLOW_VERSION = 3
DEFAULT_SIGMA = 1.0
DEFAULT_DENOISER_STRENGTH = 0.0005
DEFAULT_SEED = 1111
DEFAULT_READ_MEL_INFO_PATH = "/tmp/mel_out.json"
DEFAULT_SAVE_WAV_INFO_COPY_PATH = "/tmp/wav_out.json"
